pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        maven {
            name = 'Sponge Snapshots'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
        maven { url 'https://maven.blamejared.com' }
        maven { url "https://maven.architectury.dev/" }
    }

    plugins {
        id "org.jetbrains.kotlin.jvm" version kotlinVersion
        id "me.modmuss50.mod-publish-plugin" version "1.1.0"
        id "coffee.cypher.json-processor" version "0.1.0"
    }
}

rootProject.name = 'Hex Casting'
include("Common", "Fabric", "Neoforge")
