# This file is auto-generated by hatch-gradle-version.
# Only the value of PY_VERSION is editable.
# All changes to other values will be ignored and overwritten.

PY_VERSION = "1.0.dev0"

# Everything below this line is completely auto-generated.

GRADLE_VERSION = "0.11.1-7"
FULL_VERSION = "0.11.1.1.0rc7.dev0"
