name: Feature Request
description: Suggest an improvement or a new feature
labels:
  - enhancement
  - unconfirmed

body:
  - type: textarea
    attributes:
      label: Describe the feature
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional context
      description: Any other relevant information (eg. use cases, alternative solutions)
