# general properties/settings

modid = "hexcasting"
book_name = "thehexbook"
is_0_black = false

recipe_dirs = [
    "{fabric.generated}/data/{modid}/recipes",
    "{forge.generated}/data/{modid}/recipes",
]
default_recipe_dir = 0

# NOTE: _Raw means "don't apply variable interpolation to this value"
pattern_regex = {_Raw='HexPattern\.fromAngles\("([qweasd]+)", HexDir\.(\w+)\),\s*modLoc\("([^"]+)"\)([^;]*true\);)?'}

template = "main.html.jinja"
spoilers = [
    "hexcasting:opened_eyes",
    "hexcasting:y_u_no_cast_angy",
    "hexcasting:enlightenment",
]
blacklist = []

[template_args]
title = "Hex Book"
mod_name = "Hexcasting"
author = "petrak@, Alwinfy"
description = "The Hex Book, all in one place."
icon_href = "icon.png"
is_bleeding_edge = true
show_landing_text = true

[base_asset_urls]
hexcasting = "https://raw.githubusercontent.com/gamma-delta/HexMod/main/Common/src/main/resources"

[i18n]
lang = "en_us"
filename = "{lang}.json"
    [i18n.extra]
    "item.minecraft.amethyst_shard" = "Amethyst Shard"
    "item.minecraft.budding_amethyst" = "Budding Amethyst"
    "block.hexcasting.slate" = "Blank Slate"


# platforms

[common]
src = "../Common/src"
# NOTE: {...} is variable interpolation from the current table
package = "{src}/main/java/at/petrak/hexcasting"
resources = "{src}/main/resources"
generated = "{src}/generated/resources"
pattern_stubs = [
    # these are tables so we have the option to add extra per-stub configs (eg. regex)
    # NOTE: each ^ is like ../ in a file path (^key and ^.key are both valid)
    # the parent of an item in an array is the table containing the array, not the array
    # so in this case, {^.package} is common.package
    { file = "{^.package}/common/casting/RegisterPatterns.java" },
    { file = "{^.package}/interop/pehkui/PehkuiInterop.java" },
]

[fabric]
src = "../Fabric/src"
package = "{src}/main/java/at/petrak/hexcasting/fabric"
resources = "{src}/main/resources"
generated = "{src}/generated/resources"
pattern_stubs = [
    { file = "{^.package}/interop/gravity/GravityApiInterop.java" },
]

[forge]
src = "../Forge/src"
package = "{src}/main/java/at/petrak/hexcasting/forge"
resources = "{src}/main/resources"
generated = "{src}/generated/resources"
