modid = "hexcasting"
book = "hexcasting:thehexbook"
default_lang = "en_us"

_export_root = "src/hexdoc/_export"
resource_dirs = [  # top takes priority
    { path="{^_export_root}/resources", reexport=false },
    "{_common.src}/main/resources",
    "{_common.src}/generated/resources",
    "{_fabric.src}/main/resources",
    "{_fabric.src}/generated/resources",
    "{_forge.src}/main/resources",
    "{_forge.src}/generated/resources",
]
export_dir = "{_export_root}/generated"

# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)' }


[[pattern_stubs]]
path = "{^_common.package}/common/lib/hex/HexActions.java"
regex = "{^_pattern_regex}"

[[pattern_stubs]]
path = "{^_fabric.package}/FabricHexInitializer.kt"
regex = "{^_pattern_regex}"

[minecraft_assets]
# https://github.com/PrismarineJS/minecraft-assets/tree/83e2169afbbce40990d69fc53e5962e4a793d467/data/1.19.1
ref = "83e2169afbbce40990d69fc53e5962e4a793d467"
version = "1.19.1"

[textures]
missing = [
    "farmersdelight:skillet",
    "hexcasting:*colorizer*",
    "hexcasting:amethyst_sconce",
    "hexcasting:edified_button",
    "hexcasting:edified_pressure_plate",
    "hexcasting:edified_slab",
    "hexcasting:edified_stairs",
]

[textures.override]
"hexcasting:akashic_connector" = "hexcasting:akashic_ligature"
"hexcasting:directrix/empty" = "hexcasting:circle/directrix/empty/front_dim"
"hexcasting:focus" = "hexcasting:focus_empty"
"hexcasting:impetus/empty" = "hexcasting:circle/impetus/empty/front_dim"
"hexcasting:quenched_allay_shard" = "hexcasting:quenched_shard_0"
"hexcasting:scroll_large" = "hexcasting:scroll_pristine_large"
"hexcasting:scroll_medium" = "hexcasting:scroll_pristine_medium"
"hexcasting:scroll_small" = "hexcasting:scroll_pristine_small"
"hexcasting:scroll" = "hexcasting:scroll_pristine_large"
"hexcasting:slate_block" = "hexcasting:slate"
"hexcasting:spellbook" = "hexcasting:spellbook_empty"
"hexcasting:staff/quenched" = "hexcasting:staff/quenched_0"

[template]
static_dir = "static"
packages = ["hexdoc"]

[template.args]
mod_name = "Hex Casting"
author = "petrak@, Alwinfy"
icon_href = "logo.png"
show_landing_text = true


# platforms

[_common]
src = "../Common/src"
package = "{src}/main/java/at/petrak/hexcasting"

[_fabric]
src = "../Fabric/src"
package = "{src}/main/java/at/petrak/hexcasting/fabric"

[_forge]
src = "../Forge/src"
package = "{src}/main/java/at/petrak/hexcasting/forge"
