# general properties/settings

modid = "hexcasting"
book = "hexcasting:thehexbook"
url = "https://gamma-delta.github.io/HexMod"

is_0_black = false

resource_dirs = [
    # hot path (these are the most common directories, so put them first)
    "{_common.src}/main/resources",
    # cold path (order doesn't matter below this point)
    "{_common.src}/generated/resources",
    "{_fabric.src}/main/resources",
    "{_fabric.src}/generated/resources",
    "{_forge.src}/main/resources",
    "{_forge.src}/generated/resources",
]

# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = {"!Raw"='make\(\s*"(?P<name>[a-zA-Z0-9_\/]+)",\s*(?:new )?(?:ActionRegistryEntry|OperationAction)\(\s*HexPattern\.fromAngles\(\s*"(?P<signature>[aqweds]+)",\s*HexDir.(?P<startdir>\w+)\)'}

spoilered_advancements = [
    "hexcasting:opened_eyes",
    "hexcasting:y_u_no_cast_angy",
    "hexcasting:enlightenment",
    "hexcasting:lore/*",
]
entry_id_blacklist = []

template = "main.html.jinja"
template_dirs = []
template_packages = []


[template_args]
title = "Hex Book"
mod_name = "Hex Casting"
author = "petrak@, Alwinfy"
description = "The Hex Book, all in one place."
icon_href = "logo.png"
is_bleeding_edge = true
show_landing_text = true


[base_asset_urls]
hexcasting = "https://raw.githubusercontent.com/gamma-delta/HexMod/main/Common/src/main/resources"


[i18n]
default_lang = "en_us"
filename = "{default_lang}.flatten.json5"

[i18n.extra]
"item.minecraft.amethyst_shard" = "Amethyst Shard"
"item.minecraft.budding_amethyst" = "Budding Amethyst"
"block.hexcasting.slate" = "Blank Slate"

[i18n.keys]
use = "Right Click"
sneak = "Left Shift"
jump = "Space"


[[pattern_stubs]]
path = "{^_common.package}/common/lib/hex/HexActions.java"
regex = "{^_pattern_regex}"

[[pattern_stubs]]
path = "{^_fabric.package}/FabricHexInitializer.kt"
regex = "{^_pattern_regex}"


# platforms

[_common]
src = "../Common/src"
package = "{src}/main/java/at/petrak/hexcasting"


[_fabric]
src = "../Fabric/src"
package = "{src}/main/java/at/petrak/hexcasting/fabric"


[_forge]
src = "../Forge/src"
package = "{src}/main/java/at/petrak/hexcasting/forge"
