# project metadata

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "HexDoc" # TODO: i'm pretty sure i had funnier ideas than this
version = "0.1.0"
authors = [
    { name="Alwinfy" },
    { name="object-Object", email="object@objectobject.ca" },
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    # better CLI argument parsing
    "typed-argument-parser>=1.8.0",
    # dict-to-dataclass (TODO: switch to Pydantic)
    "dacite@git+https://github.com/mciszczon/dacite@f298260c6aedc1097c7567b1b0a61298a0ddf2a8",
]

[project.entry-points."hexdoc.Page"]
hexdoc-patchouli = "patchouli.page.pages"
hexdoc-hexcasting = "hexcasting.hex_pages"

[project.entry-points."hexdoc.Recipe"]
hexdoc-minecraft = "minecraft.recipe.recipes"
hexdoc-hexcasting = "hexcasting.hex_recipes"

[project.entry-points."hexdoc.ItemIngredient"]
hexdoc-minecraft = "minecraft.recipe.ingredients"
hexdoc-hexcasting = "hexcasting.hex_recipes"

# Hatch settings (the build backend)

[tool.hatch.metadata]
allow-direct-references = true # TODO: remove when we switch to Pydantic

[tool.hatch.build]
packages = ["src/common", "src/hexcasting", "src/minecraft", "src/patchouli"]

# tests, formatting, and (TODO:) type checking

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib"
]
markers = [
    "filename: name of file for fixtures to create",
    "file_contents: data for fixtures to write to files",
    "fixture_data: other misc data",
]

[tool.coverage.report]
include_namespace_packages = true

[tool.isort]
profile = "black"
combine_as_imports = true
