MEDIA_DUST_UNIT = 10000
MEDIA_SHARD_UNIT = 5 * MEDIA_DUST_UNIT
MEDIA_CRYSTAL_UNIT = 10 * MEDIA_DUST_UNIT

MEDIA_QUENCHED_SHARD_UNIT = 3 * MEDIA_CRYSTAL_UNIT
MEDIA_QUENCHED_BLOCK_UNIT = 4 * MEDIA_QUENCHED_SHARD_UNIT
