name: Build the web book

on:
  push:
    # Keep in sync with on.push.branches in deploy_docs.yml
    branches-ignore:
      - main
      - '1.21'
  pull_request:
  workflow_dispatch:
    inputs:
      hexdoc-release:
        description: Build in release mode
        type: boolean
  workflow_call:
    inputs:
      hexdoc-release:
        type: boolean
        required: true
    outputs:
      pages-url:
        value: ${{ jobs.build-hexdoc.outputs.pages-url }}

jobs:
  build-hexdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: read
    outputs:
      pages-url: ${{ steps.build.outputs.pages-url }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version-file: .python-version

      - uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true

      - name: Sync dependencies
        run: uv sync --locked --no-dev

      - id: build
        uses: hexdoc-dev/actions/build@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release: ${{ inputs.hexdoc-release || 'false' }}
